### ISSUE TITLE
aur4 support

### ISSUE THREAD

**Issue by jristz** [keenerd/packer#137]
sunce aur4 will now in July8 repĺace the current aur it could be a good idea make packer compatible or at least take adventage on the new aur4 git things capabilities.

Deadlinue July8 then aur 4 and normal aur will switch and old aur will be a readonly with no updates. also that could mark the point fot packet to be not maintained.

**Comment by grondinm** [comment]
see my pull request here https://github.com/keenerd/packer/pull/138 for quick dirty fix

**Comment by robclancy** [comment]
This basically makes it so I will no longer use packer since it isn't supported.

**Comment by foolishgrunt** [comment]
robclancy:
Try packer-color instead, which has implemented grondinm's patch and now works with AUR4.
https://aur4.archlinux.org/packages/packer-color/

**Comment by robclancy** [comment]
Thanks!

**Comment by Stephen304** [comment]
So it's august 8 and packer refuses to update anything. Looking at the PKGBUILD files, it looks like the aur is no longer serving pkgbuild files as finalization of the migration.

    /tmp/packertmp-1000/ttf-font-awesome.PKGBUILD: line 1: !DOCTYPE: No such file or directory
    /tmp/packertmp-1000/ttf-font-awesome.PKGBUILD: line 2: syntax error near unexpected token `newline'
    /tmp/packertmp-1000/ttf-font-awesome.PKGBUILD: line 2: `  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">'

**Comment by varemenos** [comment]
I believe this is fixed with: ed928f8

**Comment by Stephen304** [comment]
Ah, yes it is. I thought this would have been done earlier so people would get the update through packer itself, but it works either way.

**Comment by jristz** [comment]
If it fixed then close!
