### ISSUE TITLE
cannot install AUR packages

### ISSUE THREAD

**Issue by binhex** [keenerd/packer#146]
Getting the following when attempting to install rutorrent:-

[root]# packer -S rutorrent
Package `rutorrent' does not exist.

I'm seeing the same thing for package rtorrent-color

**Comment by Shookit** [comment]
Mentioned on https://aur.archlinux.org/packages/packer/ ; not sure adding v=5 to the rpc url is a good permanent fix, or just a workaround.

**Comment by Shookit** [comment]
That said, this won't necessarily work on all packages.

**Comment by binhex** [comment]
check out the reference above to the PR from another member for what looks to be a fix for v5

**Comment by Shookit** [comment]
That patch seems to work on my end for the cases I tested, just FYI.

**Comment by WurdahMekanik** [comment]
The patch from PR #145 also works for me thus far.
