### ISSUE TITLE
Packages cannot be installed

### ISSUE THREAD

**Issue by sudokode** [keenerd/packer#87]
Summary:
After installing packer as of 2013/1/18, packages fail to install because of what looks to be a glob issue.

Steps to reproduce:
1. Install a package with packer
2. Wait for install step
3. packer claims it cannot be read or found

Output example:
error: 'vte3-select-text-*.pkg.tar': could not find or read package

The package tarballs are produced, but must be manually installed from the packerbuild directory.

EDIT:
Apologies, this happened before the packer update. After installing the new packer package, things seem to work fine. Must be an old bug.

**Comment by Storm-Engineer** [comment]
Actually, as of today, with an up to date packer, I still have this exact issue with several packages.

**Comment by scippio** [comment]
Do you have enough space in temp directory?

**Comment by Storm-Engineer** [comment]
As I said I have the EXACT same issue - which means the actual files are there, and can be installed manually, as outline in the original report. So yes, I do have enough space. :D

The issue is present for a while now, but only with some packages.
